name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every 24 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: Scoince
          outputs: |
            dist/snake.svg

      - name: Move snake.svg to root folder
        run: |
          mkdir -p output
          mv dist/snake.svg output/snake.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          <img src="https://raw.githubusercontent.com/Scoince/Scoince/main/output/snake.svg" alt="Snake animation" />

