name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Scoince
          outputs: |
            dist/snake.svg

      - name: Push to main branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main  # 👈 if you want to commit the output directly to the main branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
