name: Generate Snake

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Generate the snake animation (GitHub contributions grid)
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Scoince
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Push the generated files to the `gh-pages` branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages       # <- this is now correctly pointing to gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
